CONFIG_VERSION: 1 # Do not touch, determines compatibility with different versions.
LOG_TYPE: "MINIMAL" # Change to FULL for extra logs.

# Language settings for the plugin.
Language: "EN-US"

# Configuration for the chat game intervals.
# Define how frequently the game events should occur, in seconds.
GameInterval: 300

# Minimum number of players required to start the game.
# The game will not start until this number of players have joined.
MinimumPlayers: 2